version: '3.8'
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d pgdb" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eventsource-network

  eventstore:
    image: eventstore/eventstore:20.10.2-buster-slim
    container_name: eventstore
    environment:
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PREFIXES=http://*:2113/
      - EVENTSTORE_HTTP_USE_SSL=False  # disable HTTPS
      - EVENTSTORE_INSECURE=true
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - eventstore-data:/var/lib/eventstore
    networks:
      - eventsource-network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      eventstore:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://pguser:pgpassword@postgres:5432/pgdb
      EVENTSTORE_URL: http://eventstore:2113
      NODE_ENV: development
    ports:
      - "3000:3000"
    networks:
      - eventsource-network

volumes:
  postgres-data:
  eventstore-data:

networks:
  eventsource-network:
    driver: bridge
